# Generated by Django 5.1.7 on 2025-03-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок метода')),
                ('print', models.CharField(max_length=25, verbose_name='Название метода')),
                ('description', models.TextField(verbose_name='Описание метода')),
                ('example_code_image', models.ImageField(blank=True, null=True, upload_to='methods_image/', verbose_name='Изображение примера кода')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
